src/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', CustomerSignUpView.as_view(), name='register'),
    path('vendor_register/', OwnerSignUpView.as_view(), name='vendor_register'),
    path('vendor_login/', VendorLoginView.as_view(), name='vendor_login'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('customer/', include('customers.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboards/', include('dashboards.urls')),
    path('vendor/', include('vendors.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api-auth/', include('rest_framework.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dashboards/urls.py
from django.urls import path
from .views import *

app_name = 'dashboards'
urlpatterns = [
    path('customer/', CustomerDashboardView.as_view(), name='customer_dashboard'),
    path('vendor/', VendorDashboardView.as_view(), name='vendor_dashboard'),
    path('vendor/edit/', VendorEditView.as_view(), name='vendor_edit'),
    path('customer/edit/', CustomerEditView.as_view(), name='customer_edit'),
    path('customer/comments/', CommentListView.as_view(), name='comment_list'),
    path('customer/addresses/', CustomerAddressesView.as_view(), name='customer_addresses'),
    path('customer/orders/', OrderListView.as_view(), name='customer_orders'),
    path('orders/detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('customer/addresses/create/', CustomerAddressCreateView.as_view(), name='customer_create_address'),
    path('customer/addresses/edit/', AddressEditView.as_view(), name='customer_edit_address'),
    path('customer/addresses/delete/', AddressDeleteView.as_view(), name='customer_delete_address'),
    path('vendor/detail/', DashboardVendorDetailView.as_view(), name='dashboard_vendor_detail'),
    path('vendor/product/create/', ProductCreateView.as_view(), name='product_create'),
    path('vendor/product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('vendor/product/edit/<int:pk>/', ProductEditView.as_view(), name='product_edit'),
    path('vendor/product/', ProductListView.as_view(), name='product_list'),
    path('vendor/<int:pk>/employees/', VendorEmployeeListView.as_view(), name='vendor_employee_list'),
    path('vendor/employees/<int:pk>/', DashboardVendorEmployeeDetailView.as_view(), name='employee-detail'),
    path('vendor/employee/create/', VendorEmployeeCreateView.as_view(), name='vendor_employee_create'),
    path('dashboards/vendor/<pk>/employees/<employee_pk>/update/', VendorEmployeeUpdateView.as_view(),
         name='vendor_employee_update'),
    # path('vendor-employee/<int:pk>/delete/', VendorEmployeeDeleteView.as_view(), name='vendor_employee_delete'),

]

src/orders/urls.py
from django.urls import path, include
from orders.views import *
app_name = 'orders'
urlpatterns = [
    path('api/v1/', include('orders.api.v1.urls')),
    path('cart/',CartView.as_view(), name='cart'),
    path('cart/checkout/',CheckOutView.as_view(), name='check_out'),
    path('success/',OrderSuccessView.as_view(), name='success'),
]

src/website/urls.py
from django.urls import path
from .views import *


app_name = 'website'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('Contact/', ContactView.as_view(), name='contact'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('vendors/', VendorListView.as_view(), name='vendor_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/new/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/new/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),

    path('rates/new/', RateCreateView.as_view(), name='rate_create'),
    path('rates/<int:pk>/edit/', RateUpdateView.as_view(), name='rate_update'),
    path('rates/<int:pk>/delete/', RateDeleteView.as_view(), name='rate_delete'),

    path('products/<int:pk>/comment/create/', CommentCreateView.as_view(), name='comment_create'),
    path('search/', ProductSearchView.as_view(), name='product_search'),

]

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ashion Template">
    <meta name="keywords" content="Ashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %} type="text/css">
    <link rel="stylesheet" href={% static "css/font-awesome.min.css" %} type="text/css">
    <link rel="stylesheet" href={% static "css/elegant-icons.css" %} type="text/css">
    <link rel="stylesheet" href={% static "css/jquery-ui.min.css" %} type="text/css">
    <link rel="stylesheet" href={% static "css/magnific-popup.css" %} type="text/css">
    <link rel="stylesheet" href={% static "css/owl.carousel.min.css" %} type="text/css">
    <link rel="stylesheet" href={% static "css/slicknav.min.css" %} type="text/css">
    <link rel="stylesheet" href={% static "css/style.css" %} type="text/css">
</head>

<body>
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__close">+</div>
    <ul class="offcanvas__widget">
        <li><span class="icon_search search-switch"></span></li>
        <li><a href="{% url 'website:product_search' %}"><span class="icon_heart_alt"></span>
            <div class="tip">2</div>
        </a></li>
        <li><a href="#"><span class="icon_bag_alt"></span>
            <div class="tip">2</div>
        </a></li>
    </ul>
    <div class="offcanvas__logo">
        <a href="website/index.html"><img src={% static "img/logo.png" %} alt=""></a>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__auth">
        <a href="#">Login</a>
        <a href="{% url 'accounts:register' %}">Register</a>
    </div>
</div>
<!-- Offcanvas Menu End -->
<!-- Header Section Begin -->
<header class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-3 col-lg-2">
                <div class="header__logo">
                    <a href="website/index.html"><img src={% static "img/logo.png" %} alt=""></a>
                </div>
            </div>
            <div class="col-xl-6 col-lg-7">
                <nav class="header__menu">
                    <ul>
                        <li class="active"><a href={% url "website:index" %}>خانه</a></li>
                        {#                        <li><a href="#">زنانه</a></li>#}
                        {#                        <li><a href="#">مردانه</a></li>#}
                        <li><a href={% url 'website:product_list' %}>محصولات</a></li>
                        <li><a href={% url 'website:vendor_list' %}>فروشگاه ها</a></li>
                        <li><a href={% url 'website:contact' %}>تماس با ما</a></li>
                        <li><a href={% url 'accounts:vendor_register' %}>ثبت فروشگاه</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3">
                <div class="header__right">
                    <div class="header__right__auth">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'dashboards:customer_dashboard' %}">{{ request.user.email }}</a>
                            <a href=" {% url 'accounts:logout' %}">خروج</a>
                        {% else %}
                            <a href="{% url 'accounts:login' %}">ورود</a>
                            <a href=" {% url 'accounts:register' %}">ثبت نام</a>
                        {% endif %}
                    </div>
                    <ul class="header__right__widget">
                        <li><span class="icon_search search-switch"></span></li>
                        <li><a href="{% url 'orders:cart' %}"><span class="icon_bag_alt"></span>
                            <div class="tip">2</div>
                        </a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="canvas__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-7">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="website/index.html"><img src={% static "img/logo.png" %} alt=""></a>
                    </div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        cilisis.</p>
                    <div class="footer__payment">
                        <a href="#"><img src={% static "img/payment/payment-1.png" %} alt=""></a>
                        <a href="#"><img src={% static "img/payment/payment-2.png" %} alt=""></a>
                        <a href="#"><img src={% static "img/payment/payment-3.png" %} alt=""></a>
                        <a href="#"><img src={% static "img/payment/payment-4.png" %} alt=""></a>
                        <a href="#"><img src={% static "img/payment/payment-5.png" %} alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-5">
                <div class="footer__widget">
                    <h6>Quick links</h6>
                    <ul>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Blogs</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-4">
                <div class="footer__widget">
                    <h6>Account</h6>
                    <ul>
                        <li><a href="#">My Account</a></li>
                        <li><a href="#">Orders Tracking</a></li>
                        <li><a href="#">Checkout</a></li>
                        <li><a href="#">Wishlist</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-8 col-sm-8">
                <div class="footer__newslatter">
                    <h6>NEWSLETTER</h6>
                    <form action="#">
                        <input type="text" placeholder="Email">
                        <button type="submit" class="site-btn">Subscribe</button>
                    </form>
                    <div class="footer__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <div class="footer__copyright__text">
                    <p>Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i>
                        by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
                </div>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" method="GET" action="{% url 'website:product_search' %}">
            <input type="text" id="search-input" name="q" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src={% static "js/jquery-3.3.1.min.js" %}></script>
<script src={% static "js/bootstrap.min.js" %}></script>
<script src={% static "js/jquery.magnific-popup.min.js" %}></script>
<script src={% static "js/jquery-ui.min.js" %}></script>
<script src={% static "js/mixitup.min.js" %}></script>
<script src={% static "js/jquery.countdown.min.js" %}></script>
<script src={% static "js/jquery.slicknav.js" %}></script>
<script src={% static "js/owl.carousel.min.js" %}></script>
<script src={% static "js/jquery.nicescroll.min.js" %}></script>
<script src={% static "js/main.js" %}></script>
<script src={% static "js/cart.js" %}></script>
</body>

</html>

src/templates/customer_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Kaiadmin - Bootstrap 5 Admin Dashboard</title>
    <meta
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
      name="viewport"
    />
    <link
      rel="icon"
      href="{% static 'dashboards_statics/img/kaiadmin/favicon.ico' %}"
      type="image/x-icon"
    />

    <!-- Fonts and icons -->
    <script src="{% static 'dashboards_statics/js/plugin/webfont/webfont.min.js' %}"></script>
    <script>
      WebFont.load({
        google: { families: ["Public Sans:300,400,500,600,700"] },
        custom: {
          families: [
            "Font Awesome 5 Solid",
            "Font Awesome 5 Regular",
            "Font Awesome 5 Brands",
            "simple-line-icons",
          ],
          urls: ["{% static 'dashboards_statics/css/fonts.min.css' %}"],
        },
        active: function () {
          sessionStorage.fonts = true;
        },
      });
    </script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'dashboards_statics/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'dashboards_statics/css/plugins.min.css' %}" />
    <link rel="stylesheet" href="{% static 'dashboards_statics/css/kaiadmin.min.css' %}" />

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="{% static 'dashboards_statics/css/demo.css' %}" />
  </head>
  <body>
    <div class="wrapper">
      <!-- Sidebar -->
      <div class="sidebar" data-background-color="dark">
        <div class="sidebar-logo">
          <!-- Logo Header -->
          <div class="logo-header" data-background-color="dark">
            <a href="index.html" class="logo">
              <img
                src="{% static 'dashboards_statics/img/kaiadmin/logo_light.svg' %}"
                alt="navbar brand"
                class="navbar-brand"
                height="20"
              />
            </a>
            <div class="nav-toggle">
              <button class="btn btn-toggle toggle-sidebar">
                <i class="gg-menu-right"></i>
              </button>
              <button class="btn btn-toggle sidenav-toggler">
                <i class="gg-menu-left"></i>
              </button>
            </div>
            <button class="topbar-toggler more">
              <i class="gg-more-vertical-alt"></i>
            </button>
          </div>
          <!-- End Logo Header -->
        </div>
        <div class="sidebar-wrapper scrollbar scrollbar-inner">
          <div class="sidebar-content">
            <ul class="nav nav-secondary">
                <li class="nav-item active">
                  <a href="{% url 'dashboards:customer_dashboard' %}">
                    <i class="fas fa-home"></i>
                    <p>اطلاعات کاربری</p>
                  </a>
                </li>
              <li class="nav-section">
                <span class="sidebar-mini-icon">
                  <i class="fa fa-ellipsis-h"></i>
                </span>
                <h4 class="text-section">عملیات مشتری</h4>
              </li>
                <li class="nav-item active">
                  <a href="{% url 'dashboards:customer_orders' %}">
                    <i class="fas fa-home"></i>
                    <p>سفارش ها</p>
                  </a>
                </li>
                <li class="nav-item active">
                  <a href="{% url 'dashboards:comment_list' %}">
                    <i class="fas fa-home"></i>
                    <p>نظرات</p>
                  </a>
                </li>
                <li class="nav-item active">
                  <a href="{% url 'dashboards:customer_addresses' %}">
                    <i class="fas fa-home"></i>
                    <p>آدرس ها</p>
                  </a>
                </li>
              <li class="nav-item">
                <a data-bs-toggle="collapse" href="#tables">
                  <i class="fas fa-table"></i>
                  <p>Tables</p>
                  <span class="caret"></span>
                </a>
                <div class="collapse" id="tables">
                  <ul class="nav nav-collapse">
                    <li>
                      <a href="tables/tables.html">
                        <span class="sub-item">Basic Table</span>
                      </a>
                    </li>
                    <li>
                      <a href="tables/datatables.html">
                        <span class="sub-item">Datatables</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- End Sidebar -->

      <div class="main-panel">
        <div class="main-header">
          <div class="main-header-logo">
            <!-- Logo Header -->
            <div class="logo-header" data-background-color="dark">
              <a href="index.html" class="logo">
                <img
                  src="{% static 'dashboards_statics/img/kaiadmin/logo_light.svg' %}"
                  alt="navbar brand"
                  class="navbar-brand"
                  height="20"
                />
              </a>
              <div class="nav-toggle">
                <button class="btn btn-toggle toggle-sidebar">
                  <i class="gg-menu-right"></i>
                </button>
                <button class="btn btn-toggle sidenav-toggler">
                  <i class="gg-menu-left"></i>
                </button>
              </div>
              <button class="topbar-toggler more">
                <i class="gg-more-vertical-alt"></i>
              </button>
            </div>
            <!-- End Logo Header -->
          </div>
          <!-- Navbar Header -->
          <nav
            class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom"
          >
            <div class="container-fluid">

              <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
                <li class="nav-item topbar-user dropdown hidden-caret">
                  <a
                    class="dropdown-toggle profile-pic"
                    data-bs-toggle="dropdown"
                    href="#"
                    aria-expanded="false"
                  >
                    <span class="profile-username">
                      <span class="fw-bold">{{ request.user.email }}</span>
                    </span>
                  </a>
                  <ul class="dropdown-menu dropdown-user animated fadeIn">
                    <div class="dropdown-user-scroll scrollbar-outer">
                      <li>
                        <div class="user-box">
                          <div class="u-text">
                            <h4>{{ request.user.email }}</h4>
                          </div>
                        </div>
                      </li>
                      <li>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'website:product_list' %}">فروشگاه</a>
                        <a class="dropdown-item" href="{% url 'website:index' %}">خانه</a>
                        <a class="dropdown-item" href="#">سبد خرید</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'dashboards:customer_edit' %}">ویرایش اطلاعات</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">خروج</a>
                      </li>
                    </div>
                  </ul>
                </li>
              </ul>
            </div>
          </nav>
          <!-- End Navbar -->
        </div>

        <div class="container">
          <div class="page-inner">
            {% block content %}
            {% endblock %}
          </div>
        </div>

        <footer class="footer">
          <div class="container-fluid d-flex justify-content-between">
            <nav class="pull-left">
              <ul class="nav">
                <li class="nav-item">
                  <a class="nav-link" href="http://www.themekita.com">
                    ThemeKita
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"> Help </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"> Licenses </a>
                </li>
              </ul>
            </nav>
            <div class="copyright">
              2024, made with <i class="fa fa-heart heart text-danger"></i> by
              <a href="http://www.themekita.com">ThemeKita</a>
            </div>
            <div>
              Distributed by
              <a target="_blank" href="https://themewagon.com/">ThemeWagon</a>.
            </div>
          </div>
        </footer>
      </div>
    </div>
    <!--   Core JS Files   -->
    <script src="{% static 'dashboards_statics/js/core/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'dashboards_statics/js/core/popper.min.js' %}"></script>
    <script src="{% static 'dashboards_statics/js/core/bootstrap.min.js' %}"></script>

    <!-- jQuery Scrollbar -->
    <script src="{% static 'dashboards_statics/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>

    <!-- Chart JS -->
    <script src="{% static 'dashboards_statics/js/plugin/chart.js/chart.min.js' %}"></script>

    <!-- jQuery Sparkline -->
    <script src="{% static 'dashboards_statics/js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

    <!-- Chart Circle -->
    <script src="{% static 'dashboards_statics/js/plugin/chart-circle/circles.min.js' %}"></script>

    <!-- Datatables -->
    <script src="{% static 'dashboards_statics/js/plugin/datatables/datatables.min.js' %}"></script>

    <!-- Bootstrap Notify -->
    <script src="{% static 'dashboards_statics/js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

    <!-- jQuery Vector Maps -->
    <script src="{% static 'dashboards_statics/js/plugin/jsvectormap/jsvectormap.min.js' %}"></script>
    <script src="{% static 'dashboards_statics/js/plugin/jsvectormap/world.js' %}"></script>

    <!-- Sweet Alert -->
    <script src="{% static 'dashboards_statics/js/plugin/sweetalert/sweetalert.min.js' %}"></script>

    <!-- Kaiadmin JS -->
    <script src="{% static 'dashboards_statics/js/kaiadmin.min.js' %}"></script>

    <!-- Kaiadmin DEMO methods, don't include it in your project! -->
    <script src="{% static 'dashboards_statics/js/setting-demo.js' %}"></script>
    <script src="{% static 'dashboards_statics/js/demo.js' %}"></script>
    <script>
      $("#lineChart").sparkline([102, 109, 120, 99, 110, 105, 115], {
        type: "line",
        height: "70",
        width: "100%",
        lineWidth: "2",
        lineColor: "#177dff",
        fillColor: "rgba(23, 125, 255, 0.14)",
      });

      $("#lineChart2").sparkline([99, 125, 122, 105, 110, 124, 115], {
        type: "line",
        height: "70",
        width: "100%",
        lineWidth: "2",
        lineColor: "#f3545d",
        fillColor: "rgba(243, 84, 93, .14)",
      });

      $("#lineChart3").sparkline([105, 103, 123, 100, 95, 105, 115], {
        type: "line",
        height: "70",
        width: "100%",
        lineWidth: "2",
        lineColor: "#ffa534",
        fillColor: "rgba(255, 165, 52, .14)",
      });
    </script>
  </body>
</html>