src/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', CustomerSignUpView.as_view(), name='register'),
    path('vendor_register/', OwnerSignUpView.as_view(), name='vendor_register'),
    path('vendor_login/', VendorLoginView.as_view(), name='vendor_login'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('customer/', include('customers.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboards/', include('dashboards.urls')),
    path('vendor/', include('vendors.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api-auth/', include('rest_framework.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin


# class UserManager(BaseUserManager):
#     def create_user(self, email, password=None):
#         if not email:
#             raise ValueError('email field is required')
#         user = self.model(email=email)
#         user.set_password(password)
#         user.save(using=self._db)
#         return user
#
#     def create_superuser(self, email, password):
#         user = self.create_user(email=email, password=password)
#         user.is_admin = True
#         user.save(using=self._db)
#         return user

class CustomUserManager(BaseUserManager):
    def create_user(self, email=None, phone_number=None, password=None, **extra_fields):
        if not email and not phone_number:
            raise ValueError('The Email or Phone number must be set')

        if email:
            email = self.normalize_email(email)
            user = self.model(email=email, phone_number=phone_number, **extra_fields)
        else:
            user = self.model(phone_number=phone_number, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email=None, phone_number=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        return self.create_user(email, phone_number, password, **extra_fields)


# class User(AbstractBaseUser):
#     email = models.EmailField(unique=True, max_length=50)
#     phone = models.CharField(max_length=50, unique=True)
#     first_name = models.CharField(max_length=255, null=True)
#     last_name = models.CharField(max_length=255, null=True)
#     is_active = models.BooleanField(default=True)
#     is_admin = models.BooleanField(default=False)
#
#     # ROLES
#     CUSTOMER = 0
#     OWNER = 1
#     MANAGER = 2
#     OPERATOR = 3
#
#     ROLE_CHOICES = (
#         (OWNER, "Owner"),
#         (CUSTOMER, 'Customer'),
#         (MANAGER, 'Manager'),
#         (OPERATOR, 'Operator')
#     )
#     role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)
#
#     USERNAME_FIELD = "email"
#     REQUIRED_FIELDS = []
#
#     objects = UserManager()
#
#     def __str__(self):
#         return self.email
#
#     @property
#     def is_staff(self):
#         return self.is_admin
#
#     def has_module_perms(self, app_label):
#         return True
#
#     def has_perm(self, perm, obj=None):
#         return True


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(blank=True, null=True, unique=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    def __str__(self):
        return self.email if self.email else self.phone_number


class Customer(CustomUser):
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.email


class Address(models.Model):
    zip_code = models.CharField(max_length=255, blank=True, null=True)
    detail = models.TextField()
    city = models.CharField(max_length=255)
    user = models.ForeignKey(CustomUser,related_name='addresses' ,on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.detail}, {self.city}'

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from vendors.models import Vendor, VendorEmployee
from accounts.models import Address, Customer, CustomUser
from vendors.models import VendorEmployee


# class LoginForms(forms.Form):
#
#     email = forms.EmailField()
#     password = forms.CharField(max_length=128)


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['zip_code', 'city', 'detail']


class CustomerSignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = Customer
        fields = ['email', 'phone_number', 'first_name', 'last_name', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        if commit:
            user.save()
        return user


class VendorOwnerSignUpForm(UserCreationForm):
    vendor_name = forms.CharField(max_length=255)
    zip_code = forms.CharField(max_length=255, required=False)
    detail = forms.CharField(widget=forms.Textarea, required=True)
    city = forms.CharField(max_length=255, required=True)

    class Meta:
        model = VendorEmployee
        fields = ['email', 'phone_number', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = 'owner'

        if commit:
            user.save()

        address = Address.objects.create(
            zip_code=self.cleaned_data['zip_code'],
            detail=self.cleaned_data['detail'],
            city=self.cleaned_data['city'],
            user=user
        )

        vendor = Vendor.objects.create(
            name=self.cleaned_data['vendor_name'],
            address=address,
            owner=user
        )

        user.vendor = vendor
        user.save()

        return user


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(label='Email or Phone')

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            try:
                user = CustomUser.objects.filter(email=username).first() or \
                       CustomUser.objects.filter(phone_number=username).first()

                if user and user.check_password(password):
                    self.user_cache = user
                else:
                    raise forms.ValidationError("اطلاعات وارد شده نامعتبر است")
            except CustomUser.DoesNotExist:
                raise forms.ValidationError("اطلاعات وارد شده نامعتبر است")

        return self.cleaned_data

src/accounts/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, FormView, UpdateView, DetailView, ListView
from accounts.forms import *
from .forms import *
from django.contrib.auth import authenticate, login


# class CustomLoginView(View):
#     template_name = 'login.html'
#
#     def get(self, request):
#         form = CustomLoginForm()
#         return render(request, self.template_name, {'form': form})
#
#     def post(self, request):
#         form = CustomLoginForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data.get('email')
#             password = form.cleaned_data.get('password')
#             user = authenticate(username=email, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('website:index')
#             else:
#                 form.add_error(None, 'Invalid email or password.')
#         return render(request, self.template_name, {'form': form})


# def logoutview(request):
#     logout(request)
#     return redirect('website:index')

class CustomLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('website:index')


class CustomerSignUpView(CreateView):
    model = Customer
    form_class = CustomerSignUpForm
    template_name = 'accounts/register_customer.html'
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class CustomLoginView(FormView):
    form_class = CustomLoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('website:index')

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super().form_valid(form)


class VendorLoginView(FormView):
    form_class = CustomLoginForm
    template_name = 'accounts/vendor_login.html'
    success_url = reverse_lazy('dashboards:vendor_dashboard')

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super().form_valid(form)


class OwnerSignUpView(CreateView):
    form_class = VendorOwnerSignUpForm
    template_name = 'accounts/vendor_register.html'
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        form.save()
        return redirect('accounts:login')

src/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First HTML Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <section class="vh-100" style="background-color: #dab2bb;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
              <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                  <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                      alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                  </div>
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
      
                      <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid gap-2">
                          <input type="submit" value="Login" class="btn btn-primary btn-lg">
                          <a href="{% url 'accounts:vendor_login' %}" class="btn btn-secondary btn-lg">Vendor Login</a>
                        </div>
                      </form>
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

src/templates/accounts/register_customer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create an Account</title>
    <link rel="stylesheet" href="css/register.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .card {
            max-width: 500px; /* Set a maximum width for the card */
            margin: auto; /* Center the card horizontally */
            padding: 2rem; /* Adjust padding to reduce height */
        }
        .vh-100 {
            height: auto; /* Allow the section to adjust its height */
        }
        .mask {
            padding: 2rem; /* Adjust padding for the mask */
        }
    </style>
</head>
<body>
    <section class="vh-100 bg-image"
    style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-6 col-lg-5">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body">
                                <h2 class="text-uppercase text-center mb-4">Create an account</h2>
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="register">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

src/templates/accounts/vendor_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First HTML Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <section class="vh-100" style="background-color: #dab2bb;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
              <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                  <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                      alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                  </div>
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">

                      <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid gap-2">
                          <input type="submit" value="Login" class="btn btn-primary btn-lg">
                          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-lg">Customer Login</a>
                        </div>
                      </form>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

src/templates/accounts/vendor_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First HTML Page</title>
    <link rel="stylesheet" href="css/vendor_register.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <section class="h-100 bg-dark">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card card-registration my-4">
          <div class="row g-0">
            <div class="col-xl-6 d-none d-xl-block">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img4.webp"
                alt="Sample photo" class="img-fluid"
                style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;" />
            </div>
            <div class="col-xl-6">
              <div class="card-body p-md-5 text-black">
                <h3 class="mb-5 text-uppercase">Vendor registration form</h3>
                  
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="register_vendor">
                </form>
                  
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>